services:
  taskmanager-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./taskmanager-backend:/taskmanager-backend

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
