services:
  taskmanager-backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./taskmanager-backend:/taskmanager-backend
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=dbuser
      - DB_PASS=dbpass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass