services:
  taskmanager-backend:
    build:
      context: .
      dockerfile: taskmanager-backend/Dockerfile.django
    ports:
      - "8000:8000"
    volumes:
      - ./taskmanager-backend:/app
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - BOT_TOKEN=8050730418:AAHagLyhx4A0ilLRYTc2y0gYkFwxfD3hCKQ
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
      - redis

  database:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: taskmanager-backend/Dockerfile.django
    volumes:
      - ./taskmanager-backend:/app
    working_dir: /app
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - BOT_TOKEN=8050730418:AAHagLyhx4A0ilLRYTc2y0gYkFwxfD3hCKQ
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A taskmanager worker -P threads
    depends_on:
      - database
      - redis

  beat:
    build:
      context: .
      dockerfile: taskmanager-backend/Dockerfile.django
    volumes:
      - ./taskmanager-backend:/app
    working_dir: /app
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - BOT_TOKEN=8050730418:AAHagLyhx4A0ilLRYTc2y0gYkFwxfD3hCKQ
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A taskmanager beat
    depends_on:
      - database
      - redis

  telegram-bot:
    build:
      context: .
      dockerfile: bot/Dockerfile.bot
    volumes:
      - ./bot:/bot
    working_dir: /bot
    environment:
      - BOT_TOKEN=8050730418:AAHagLyhx4A0ilLRYTc2y0gYkFwxfD3hCKQ
    command: sh -c "python main.py"
    depends_on:
      - taskmanager-backend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: